#!/usr/bin/env python2
import sys
import os
import commands

CURDIR = os.path.realpath(os.curdir)
FILEDIR = os.path.realpath(os.path.dirname(__file__))
TEMPLATE = os.path.join(FILEDIR, 'template.py')

if len(sys.argv) < 4:
    print >> sys.stderr, "Usage: "+os.path.basename(sys.argv[0])+" <binary> <host> <port> [<libc>]"
else:
    os.chdir(FILEDIR)
    args = {
            'binary': sys.argv[1],
            'host': sys.argv[2],
            'port': sys.argv[3]
            }

    READELF = None
    if 'darwin' in sys.platform:
        READELF = 'greadelf'
    elif 'linux' in sys.platform:
        READELF = 'readelf'
    res = commands.getoutput("{0} -h ".format(READELF)+os.path.join(CURDIR, args['binary']))

    if "ELF32" in res:
        args['arch'] = 'i386'
    elif "ELF64" in res:
        args['arch'] = 'amd64'
    else:
        args['arch'] = 'unknown'

    if len(sys.argv) > 4:
        args['libc'] = sys.argv[4]
    else:
        args['libc'] = ''

    os.chdir(CURDIR)
    open('exploit.py', 'w').write(open(TEMPLATE).read().format(**args))

sys.exit(0)
