#!/usr/bin/env python2
import sys
import os
import commands
import string


CURDIR = os.path.realpath(os.curdir)
FILEDIR = os.path.realpath(os.path.dirname(__file__))
TEMPLATE = os.path.join(FILEDIR, 'template.py')

if len(sys.argv) < 4:
    print >> sys.stderr, "Usage: "+os.path.basename(sys.argv[0])+" <binary> <host> <port> [<libc>]"
else:
    os.chdir(FILEDIR)
    args = {
        'binary': sys.argv[1],
        'host': sys.argv[2],
        'port': sys.argv[3],
        'libc': sys.argv[4] if len(sys.argv) > 4 else ''
    }
    os.chdir(CURDIR)
    if os.path.exists('exploit.py'):
        if raw_input("overwrite exploit.py? [y/N] ").strip().lower() != 'y':
            sys.exit(1)
    open('exploit.py', 'w').write(string.Template(open(TEMPLATE).read()).substitute(args))

sys.exit(0)